In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]],
      shape=(1372, 5))

In [4]:
labels = data[:,4]

In [5]:
features = data[:,0:4]

In [6]:
X = features # by convention
y = labels # by convention

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

D:\Projectes\Cursos\ComputerVisionWithPython\ComputerVisionWithPythonSrc\.venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [18]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - 21ms/step - accuracy: 0.7552 - loss: 0.6368
Epoch 2/50
29/29 - 0s - 2ms/step - accuracy: 0.7704 - loss: 0.6161
Epoch 3/50
29/29 - 0s - 2ms/step - accuracy: 0.7432 - loss: 0.6018
Epoch 4/50
29/29 - 0s - 2ms/step - accuracy: 0.7236 - loss: 0.5886
Epoch 5/50
29/29 - 0s - 2ms/step - accuracy: 0.7563 - loss: 0.5743
Epoch 6/50
29/29 - 0s - 2ms/step - accuracy: 0.7704 - loss: 0.5579
Epoch 7/50
29/29 - 0s - 2ms/step - accuracy: 0.7758 - loss: 0.5420
Epoch 8/50
29/29 - 0s - 2ms/step - accuracy: 0.7748 - loss: 0.5265
Epoch 9/50
29/29 - 0s - 2ms/step - accuracy: 0.7780 - loss: 0.5126
Epoch 10/50
29/29 - 0s - 2ms/step - accuracy: 0.7943 - loss: 0.4983
Epoch 11/50
29/29 - 0s - 2ms/step - accuracy: 0.7900 - loss: 0.4840
Epoch 12/50
29/29 - 0s - 2ms/step - accuracy: 0.8085 - loss: 0.4699
Epoch 13/50
29/29 - 0s - 2ms/step - accuracy: 0.8226 - loss: 0.4559
Epoch 14/50
29/29 - 0s - 2ms/step - accuracy: 0.8237 - loss: 0.4421
Epoch 15/50
29/29 - 0s - 2ms/step - accuracy: 0.8335 - l

In [22]:
# model.predict_classes(scaled_X_test)
# predict_classes was removed in TensorFlow 2.6.
predict_x=model.predict(scaled_X_test)
classes_x=np.argmax(predict_x,axis=1)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [23]:
classes_x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [24]:
# evaluate the model
model.metrics_names

['loss', 'compile_metrics']

In [25]:
from sklearn.metrics import confusion_matrix,classification_report

In [26]:
confusion_matrix(y_test, classes_x)

array([[257,   0],
       [196,   0]])

In [27]:
print(classification_report(y_test, classes_x))

              precision    recall  f1-score   support

         0.0       0.57      1.00      0.72       257
         1.0       0.00      0.00      0.00       196

    accuracy                           0.57       453
   macro avg       0.28      0.50      0.36       453
weighted avg       0.32      0.57      0.41       453



D:\Projectes\Cursos\ComputerVisionWithPython\ComputerVisionWithPythonSrc\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
D:\Projectes\Cursos\ComputerVisionWithPython\ComputerVisionWithPythonSrc\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
D:\Projectes\Cursos\ComputerVisionWithPython\ComputerVisionWithPythonSrc\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.