In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [5]:
myarray

array([1, 2, 3])

In [6]:
type(myarray)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10,20,4)

array([10, 14, 18])

In [10]:
l = np.arange(10)

In [11]:
type(l)

numpy.ndarray

In [12]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [13]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [14]:
arr.max()

np.int32(95)

In [15]:
arr.argmax()

np.int64(0)

In [16]:
mat=np.arange(0,100).reshape(10,10)

In [17]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [18]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [24]:
mycopy = mat.copy()

In [20]:
mcopy

NameError: name 'mcopy' is not defined

In [25]:
mycopy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])